Ansible 2
Otus-DevOps-2022-02/salenjhons_infra pull request #11
Opened 2022-04-23 15:20 UTC by salenjhons

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2022-04-24 19:46 UTC, salenjhons commented
Привествую.
Не могу понять почему вадиладация валится на проверкм синтаксиси ансибла и пакера.

2022-04-25 08:27 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
оставил комментарий к файлу, так же дополнительно посмотрите на конфигурацию пакера
ДЗ возвращаю на доработку

2022-04-25 08:27 UTC, mrgreyves commented on ansible/reddit_app_multiple_plays.yml
> +       become: true
Вот тут поломался хендлер
Отступы не поплыли

2022-04-25 17:47 UTC, salenjhons commented on ansible/reddit_app_multiple_plays.yml
> +       become: true
Спасибо за наводку.
Проскочило)

2022-04-26 10:58 UTC, mrgreyves approved these changes
Здравствуйте!)
Апрув =)

2022-04-26 13:50 UTC, merged