Ansible-3
Otus-DevOps-2022-02/salenjhons_infra pull request #12
Opened 2022-05-01 13:53 UTC by salenjhons

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2022-05-02 09:45 UTC, salenjhons commented
Здравствуйте!
Не понимаю почему ansible-lint ругается на проблемы.

2022-05-02 12:04 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/34331259/166230748-81d4c4dd-86dc-4b52-9644-0368897eee8b.png">
Линтер правильно ругается, тут как раз все видно =)
Это не большие правки, дз нужно доработать =)

2022-05-02 14:16 UTC, salenjhons commented
Спасибо!)

2022-05-04 09:33 UTC, mrgreyves approved these changes
Здравствуйте!)
Апрув ^_^

2022-05-10 15:41 UTC, merged